language: java
jdk:
    - openjdk11
services:
    - mysql
    - docker
before_install:
    - docker pull rabbitmq:3-management
    - docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=user -d rabbitmq:3-management
    - mysql -u root < server/src/main/resources/data.sql
install:
    - cd server
    - mvn install -DskipTests -Dmaven.javadoc.skip
script: 
    - mvn test -Dspring.profiles.active=test
