language: java
jdk:
    - openjdk11
services:
    - mysql
    - docker
before_install:
    - docker pull rabbitmq:3-management
    - docker run --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=user -d rabbitmq:3-management
    - mysql -u root -e 'CREATE DATABASE target CHARACTER SET utf8mb4;'
    - mysql -u root -D target < server/src/main/resources/data.sql
    - mysql -u root -e 'DROP USER IF EXISTS admin@"%";'
    - mysql -u root -e 'FLUSH PRIVILEGES;'
    - mysql -u root -e 'CREATE USER admin@"%" identified by "admin";'
    - mysql -u root -e 'GRANT ALL PRIVILEGES ON target.* to admin@"%" WITH GRANT OPTION;'
install:
    - cd server
    - mvn install -DskipTests -Dmaven.javadoc.skip
script: 
    - mvn test -Dspring.profiles.active=test
