version: "3"
services:
  redis:
    image: redis
    networks:
      - naive
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Shanghai
    volumes:
      - ./server/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    networks:
      - naive
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - naive
  server:
    image: xlui/target-server
    ports:
      - 127.0.0.1:8080:8080
    links:
      - redis
      - mysql
      - rabbitmq
    networks:
      - naive

networks:
    naive:
        driver: bridge
